---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/content-repository/src/main/fabric8/icon.svg
      prometheus.io/port: "9180"
      prometheus.io/scrape: "true"
      fabric8.io/git-commit: 5c453edb04f1c8d5fc34228a671300d8523b0274
      fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/content-repository
      fabric8.io/scm-url: http://github.com/fabric8io/fabric8-devops/content-repository
      fabric8.io/git-branch: release-v2.2.330
      fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/content-repository
      fabric8.io/scm-tag: fabric8-devops-2.0.1
    labels:
      provider: fabric8
      project: content-repository
      version: 2.2.330
      group: io.fabric8.devops.apps
      expose: "true"
    name: content-repository
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      project: content-repository
      provider: fabric8
      group: io.fabric8.devops.apps
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: standard
    labels:
      provider: fabric8
      project: content-repository
      version: 2.2.330
      group: io.fabric8.devops.apps
    name: content-repository
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/content-repository/src/main/fabric8/icon.svg
      fabric8.io/git-commit: 5c453edb04f1c8d5fc34228a671300d8523b0274
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=content-repository&var-version=2.2.330
      fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/content-repository
      fabric8.io/scm-url: http://github.com/fabric8io/fabric8-devops/content-repository
      fabric8.io/git-branch: release-v2.2.330
      fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/content-repository
      fabric8.io/scm-tag: fabric8-devops-2.0.1
    labels:
      provider: fabric8
      project: content-repository
      version: 2.2.330
      group: io.fabric8.devops.apps
    name: content-repository
  spec:
    replicas: 1
    selector:
      project: content-repository
      provider: fabric8
      version: 2.2.330
      group: io.fabric8.devops.apps
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 5c453edb04f1c8d5fc34228a671300d8523b0274
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=content-repository&var-version=2.2.330
          fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/content-repository
          fabric8.io/scm-url: http://github.com/fabric8io/fabric8-devops/content-repository
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/content-repository/src/main/fabric8/icon.svg
          fabric8.io/git-branch: release-v2.2.330
          fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/content-repository
          fabric8.io/scm-tag: fabric8-devops-2.0.1
        labels:
          provider: fabric8
          project: content-repository
          version: 2.2.330
          group: io.fabric8.devops.apps
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: fabric8/alpine-caddy:2.2.330
          imagePullPolicy: IfNotPresent
          name: content-repository
          ports:
          - containerPort: 8080
            name: http
          - containerPort: 9180
            name: prometheus
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          volumeMounts:
          - mountPath: /var/www/html
            name: content
            readOnly: false
        volumes:
        - name: content
          persistentVolumeClaim:
            claimName: content-repository
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      provider: fabric8
      project: content-repository
      version: 2.2.330
      group: io.fabric8.devops.apps
    name: content-repository
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: content-repository
