---
apiVersion: v1
kind: Template
metadata:
objects:
- apiVersion: v1
  kind: RoleBindingRestriction
  metadata:
    name: dsaas-access-users
  spec: 
    userrestriction:
      users: 
      - ${PROJECT_ADMIN_USER}
      - system:serviceaccount:${PROJECT_NAME}-jenkins:jenkins
- apiVersion: v1
  kind: RoleBindingRestriction
  metadata:
    name: dsaas-access-groups
  spec: 
    grouprestriction:
      groups: 
      - system:serviceaccounts:${PROJECT_NAME}-jenkins
- apiVersion: v1
  kind: RoleBindingRestriction
  metadata:
    name: dsaas-access-sa-ns
  spec: 
    serviceaccountrestriction:
      namespaces: 
      - ${PROJECT_NAME}-jenkins
parameters:
- name: PROJECT_NAME