version: '2'

services:
  db:
    image: registry.centos.org/postgresql/postgresql:9.6
    ports:
      - "5434:5432"
    environment:
      # POSTGRESQL_USER: postgres
      # POSTGRESQL_PASSWORD: mysecretpassword
      # POSTGRESQL_DATABASE: tenant
      POSTGRESQL_ADMIN_PASSWORD: mysecretpassword
