apiVersion: v1
kind: Template
metadata:
  name: f8tenant-config
  creationTimestamp: null
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: f8tenant
  type: Opaque
  data:
    postgres.host: bG9jYWxob3N0Cg==
    postgres.port: NTQzMgo=
    postgres.user: cG9zdGdyZXMK
    postgres.database: cG9zdGdyZXMK
    postgres.password: bXlzZWNyZXRwYXNzc3dvcmQK
    template.recommender.api.token: eHh4eA==
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: f8tenant
  type: Opaque
  data:
    postgres.connection.maxidle: '30'
    postgres.connection.maxopen: '30'
    keycloak.url: http://keycloak/
    wit.url: http://api.wit/api
    auth.url: https://auth.openshift.io
    openshift.tenant.masterurl: https://openshift.default.svc.cluster.local
    template.recommender.external.name: recommender.api.prod-preview.openshift.io
    template.domain: d800.free-int.openshiftapps.com
    template.che.multitenant.server: https://che.prod-preview.openshift.io