---
apiVersion: v1
kind: Template
metadata:
  name: fabric8-tenant-service
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: f8tenant
    name: f8tenant
  spec:
    replicas: 2
    selector:
      app: f8tenant
      deploymentconfig: f8tenant
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: f8tenant
          deploymentconfig: f8tenant
      spec:
        containers:
        - env:
          - name: F8_POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: f8tenant
                key: postgres.host
          - name: F8_POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: f8tenant
                key: postgres.port
          - name: F8_POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: f8tenant
                key: postgres.user
          - name: F8_POSTGRES_DATABASE
            valueFrom:
              secretKeyRef:
                name: f8tenant
                key: postgres.database
          - name: F8_POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: f8tenant
                key: postgres.password
          - name: F8_POSTGRES_CONNECTION_MAXIDLE
            valueFrom:
              configMapKeyRef:
                name: f8tenant
                key: postgres.connection.maxidle
          - name: F8_POSTGRES_CONNECTION_MAXOPEN
            valueFrom:
              configMapKeyRef:
                name: f8tenant
                key: postgres.connection.maxopen
          - name: F8_KEYCLOAK_URL
            valueFrom:
              configMapKeyRef:
                name: f8tenant
                key: keycloak.url
          - name: F8_AUTH_URL
            valueFrom:
              configMapKeyRef:
                name: f8tenant
                key: auth.url
          - name: F8_CLUSTER_REFRESH_DELAY
            valueFrom:
              configMapKeyRef:
                name: f8tenant
                key: cluster.refresh.delay
          - name: F8_TEMPLATE_RECOMMENDER_EXTERNAL_NAME
            valueFrom:
              configMapKeyRef:
                name: f8tenant
                key: template.recommender.external.name
          - name: F8_TEMPLATE_RECOMMENDER_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: f8tenant
                key: template.recommender.api.token
          - name: F8_TEMPLATE_DOMAIN
            valueFrom:
              configMapKeyRef:
                name: f8tenant
                key: template.domain
          - name: F8_TEMPLATE_CHE_MULTITENANT_SERVER
            valueFrom:
              configMapKeyRef:
                name: f8tenant
                key: template.che.multitenant.server
          - name: F8_TEMPLATE_JENKINS_ROOT_URL
            valueFrom:
              configMapKeyRef:
                name: f8tenant
                key: template.jenkins.root.url
          - name: F8_SERVICE_ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                name: f8tenant
                key: service.account.id
          - name: F8_SERVICE_ACCOUNT_SECRET
            valueFrom:
              secretKeyRef:
                name: f8tenant
                key: service.account.secret
          - name: F8_AUTH_TOKEN_KEY
            valueFrom:
              secretKeyRef:
                name: f8tenant
                key: auth.token.key
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: f8tenant
                key: sentry.dsn
          - name: F8_ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: f8tenant
                key: environment
          - name: F8_AUTOMATED_UPDATE_ENABLED
            value: ${f8_automated_update_enabled}
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: f8tenant
          ports:
          - containerPort: 8080
            protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/status
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/status
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 1Gi
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    name: f8tenant
  spec:
    ports:
      - protocol: TCP
        port: 80
        targetPort: 8080
    selector:
      deploymentconfig: f8tenant
parameters:
- name: IMAGE
  value: quay.io/openshiftio/rhel-fabric8-services-fabric8-tenant
- name: IMAGE_TAG
  value: latest
- name: f8_automated_update_enabled
  value: 'false'
