---
apiVersion: v1
kind: Template
metadata:
  labels:
    provider: fabric8
    project: fabric8-tenant-user
    version: ${COMMIT}
  name: fabric8-tenant-user
objects:
- apiVersion: v1
  kind: ProjectRequest
  metadata:
    annotations:
      openshift.io/description: ${USER_NAME}
      openshift.io/display-name: ${USER_NAME}
      openshift.io/requester: ${PROJECT_REQUESTING_USER}
    labels:
      provider: fabric8
      project: fabric8-tenant-user
      version: ${COMMIT}
    name: ${USER_NAME}
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      app: fabric8-tenant-user
      provider: fabric8
      version: ${COMMIT}
    name: user-edit
    namespace: ${USER_NAME}
  roleRef:
    name: edit
  subjects:
  - kind: User
    name: ${PROJECT_USER}
  userNames:
  - ${PROJECT_USER}
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      app: fabric8-tenant-user
      provider: fabric8
      version: ${COMMIT}
    name: user-view
    namespace: ${USER_NAME}
  roleRef:
    name: view
  subjects:
  - kind: User
    name: ${PROJECT_USER}
  userNames:
  - ${PROJECT_USER}
- apiVersion: v1
  kind: RoleBindingRestriction
  metadata:
    labels:
      app: fabric8-tenant-user
      provider: fabric8
      version: ${COMMIT}
    name: dsaas-access-users
    namespace: ${USER_NAME}
  spec:
    userrestriction:
      users:
      - ${PROJECT_ADMIN_USER}
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      app: fabric8-tenant-user
      provider: fabric8
      version: ${COMMIT}
    name: dsaas-admin
    namespace: ${USER_NAME}
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: ${PROJECT_ADMIN_USER}
  userNames:
  - ${PROJECT_ADMIN_USER}
parameters:
- name: USER_NAME
  value: developer
- name: PROJECT_ADMIN_USER
  value: developer
- name: PROJECT_REQUESTING_USER
  value: system:admin
- name: EXTERNAL_DOCKER_REGISTRY_URL
- name: FABRIC8_CONSOLE_URL
- name: KEYCLOAK_URL
- name: COMMIT
  value: 123abc