---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: LimitRange
  metadata:
    labels:
      app: fabric8-tenant-jenkins-quotas
      provider: fabric8
      version: ${COMMIT_QUOTAS}
    name: resource-limits
    namespace: ${USER_NAME}-jenkins
  spec:
    limits:
    - max:
        cpu: "3"
        memory: 1536Mi
      min:
        cpu: 17m
        memory: 90Mi
      type: Pod
    - default:
        cpu: "1"
        memory: 512Mi
      defaultRequest:
        cpu: 60m
        memory: 307Mi
      max:
        cpu: "3"
        memory: 1536Mi
      min:
        cpu: 17m
        memory: 90Mi
      type: Container
    - max:
        storage: 1Gi
      min:
        storage: 1Gi
      type: PersistentVolumeClaim
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    labels:
      app: fabric8-tenant-jenkins-quotas
      provider: fabric8
      version: ${COMMIT_QUOTAS}
    name: compute-resources
    namespace: ${USER_NAME}-jenkins
  spec:
    hard:
      limits.cpu: "2"
      limits.memory: 1Gi
    scopes:
    - NotTerminating
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    labels:
      app: fabric8-tenant-jenkins-quotas
      provider: fabric8
      version: ${COMMIT_QUOTAS}
    name: compute-resources-timebound
    namespace: ${USER_NAME}-jenkins
  spec:
    hard:
      limits.cpu: "4"
      limits.memory: 2Gi
    scopes:
    - Terminating
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    labels:
      app: fabric8-tenant-jenkins-quotas
      provider: fabric8
      version: ${COMMIT_QUOTAS}
    name: object-counts
    namespace: ${USER_NAME}-jenkins
  spec:
    hard:
      persistentvolumeclaims: "2"
      replicationcontrollers: "20"
      secrets: "40"
      services: "5"
parameters:
- name: USER_NAME
  value: developer
- name: COMMIT_QUOTAS
  value: 123abc